# Generated by Django 4.2.4 on 2024-04-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StouplNaSamce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.IntegerField()),
                ('gameId', models.IntegerField()),
                ('color', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFliped', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'LEKNIN'), (2, 'KOMAR'), (3, 'BAHNO'), (4, 'STIKA'), (5, 'RAKOS'), (60, 'MODRY_SAMEC'), (61, 'FIALOVY_SAMEC'), (62, 'CERVENY_SAMEC'), (63, 'RUZOVY_SAMEC'), (64, 'ZELENY_SAMEC'), (65, 'ZLUTY_SAMEC'), (7, 'KLADA')])),
                ('backgroundType', models.IntegerField(choices=[(1, 'BEZ_STIKY'), (2, 'STIKA_DOLE'), (3, 'STIKA_NAHORE')])),
                ('number', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='kvak.board')),
            ],
        ),
        migrations.CreateModel(
            name='Žába',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isQueen', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaby', to='kvak.player')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaby', to='kvak.tile')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstOnMove', models.BooleanField(default=True)),
                ('moveCount', models.IntegerField(default=0)),
                ('isOver', models.BooleanField(default=False)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kvak.board')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_reverse', to='kvak.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_reverse', to='kvak.player')),
            ],
        ),
    ]
