# Generated by Django 4.2.11 on 2024-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvak', '0002_žába_can_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='žába',
            name='can_move',
        ),
        migrations.AddField(
            model_name='žába',
            name='stunned',
            field=models.IntegerField(default=0),
        ),
    ]
