# Generated by Django 4.2.4 on 2024-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvak', '0003_remove_žába_can_move_žába_stunned'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='komar_frog',
            field=models.IntegerField(default=-1),
        ),
    ]
